/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pm.presentation.example.lib;

import java.nio.file.Files;
import java.nio.file.Path;
import javax.swing.ListModel;
import javax.swing.UIManager;
import javax.swing.tree.TreeSelectionModel;
//import javax.swing.ListModel;
/**
 *
 * @author user
 */
public class FilesMainPanel extends javax.swing.JPanel {

    /**
     * Creates new form FilesMainPanel
     */
    FilesTreeNode rootNode;
    private final FilesListCellRenderer listCellRenderer = new FilesListCellRenderer();
    public FilesMainPanel() {
                        rootNode = new FilesTreeNode(null); 
        rootNode.loadChildren(); 

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        fsList = new pm.presentation.example.lib.FilesList(null);
        fsList.setCellRenderer(listCellRenderer);
        jScrollPane1 = new javax.swing.JScrollPane();
        fsTree = new pm.presentation.example.lib.FilesTree(rootNode);
        fsTree.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);

        jScrollPane2.setViewportView(fsList);

        jScrollPane1.setViewportView(fsTree);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
            .addComponent(jScrollPane2)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void fsTreeValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_fsTreeValueChanged
        FilesTreeNode node = (FilesTreeNode) evt.getPath().getLastPathComponent();
        if (node.getUserObject() == null || Files.isDirectory((Path) node.getUserObject())) {
            fsList.loadDirContents((Path) node.getUserObject());
        }
    }//GEN-LAST:event_fsTreeValueChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private pm.presentation.example.lib.FilesList fsList;
    private pm.presentation.example.lib.FilesTree fsTree;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
